import { Inter } from 'next/font/google';
import './globals.css';
import SnackBarProvider from './contexts/SnackBarContext';
const inter = Inter({ subsets: ['latin'] });
export const metadata = {
  title: 'Phoenix - AI powered chat bot',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <SnackBarProvider>{children}</SnackBarProvider>
      </body>
    </html>
  );
}
