import React from "react";
import Register from "@/components/register";



export const metadata = {
  title: "Create An Account",
  description: "Generated by create next app",
};



const page = () => {
  return(
    <>
    <Register/>
    </>
    )
};

export default page;
